from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
)
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics


def clean_text(text: str) -> str:
    """
    ReportLab Paragraph uses XML-like markup.
    So we escape special characters safely.
    """
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def get_pdf_styles():
    styles = getSampleStyleSheet()

    styles.add(
        ParagraphStyle(
            name="ReportTitle",
            parent=styles["Title"],
            fontSize=22,
            leading=28,
            spaceAfter=20,
            textColor=colors.HexColor("#1F2937"),
        )
    )

    styles.add(
        ParagraphStyle(
            name="SectionHeading",
            parent=styles["Heading1"],
            fontSize=16,
            leading=20,
            spaceBefore=14,
            spaceAfter=10,
            textColor=colors.HexColor("#111827"),
        )
    )

    styles.add(
        ParagraphStyle(
            name="SubHeading",
            parent=styles["Heading2"],
            fontSize=13,
            leading=17,
            spaceBefore=10,
            spaceAfter=8,
            textColor=colors.HexColor("#374151"),
        )
    )

    styles.add(
        ParagraphStyle(
            name="BodyTextCustom",
            parent=styles["BodyText"],
            fontSize=10.5,
            leading=15,
            spaceAfter=6,
        )
    )

    styles.add(
        ParagraphStyle(
            name="BulletTextCustom",
            parent=styles["BodyText"],
            fontSize=10.5,
            leading=15,
            leftIndent=18,
            bulletIndent=8,
            spaceAfter=5,
        )
    )

    styles.add(
        ParagraphStyle(
            name="CodeText",
            parent=styles["BodyText"],
            fontName="Courier",
            fontSize=9,
            leading=12,
            backColor=colors.HexColor("#F3F4F6"),
            borderColor=colors.HexColor("#E5E7EB"),
            borderWidth=0.5,
            borderPadding=5,
            spaceAfter=6,
        )
    )

    return styles


def add_footer(canvas, doc):
    canvas.saveState()

    width, height = A4

    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)

    footer_text = "Generated by Agentic Data Parsing Engine"
    page_text = f"Page {doc.page}"

    canvas.drawString(inch, 0.45 * inch, footer_text)
    canvas.drawRightString(width - inch, 0.45 * inch, page_text)

    canvas.restoreState()


def markdown_line_to_flowable(line: str, styles):
    line = line.strip()

    if not line:
        return Spacer(1, 8)

    if line == "---":
        return Spacer(1, 14)

    if line.startswith("# "):
        text = clean_text(line.replace("# ", "", 1))
        return Paragraph(text, styles["ReportTitle"])

    if line.startswith("## "):
        text = clean_text(line.replace("## ", "", 1))
        return Paragraph(text, styles["SectionHeading"])

    if line.startswith("### "):
        text = clean_text(line.replace("### ", "", 1))
        return Paragraph(text, styles["SubHeading"])

    if line.startswith("- "):
        text = clean_text(line.replace("- ", "", 1))
        return Paragraph(text, styles["BulletTextCustom"], bulletText="•")

    if line.startswith("```"):
        return Spacer(1, 4)

    if line.startswith("`") and line.endswith("`"):
        text = clean_text(line.replace("`", ""))
        return Paragraph(text, styles["CodeText"])

    # Basic markdown cleanup
    line = line.replace("**", "")
    line = line.replace("`", "")

    return Paragraph(clean_text(line), styles["BodyTextCustom"])


def generate_pdf_from_markdown(markdown_path, pdf_path=None):
    markdown_path = Path(markdown_path)

    if not markdown_path.exists():
        raise FileNotFoundError(f"Markdown report not found: {markdown_path}")

    if pdf_path is None:
        pdf_path = markdown_path.with_suffix(".pdf")

    pdf_path = Path(pdf_path)
    pdf_path.parent.mkdir(parents=True, exist_ok=True)

    with open(markdown_path, "r", encoding="utf-8") as file:
        markdown_content = file.read()

    styles = get_pdf_styles()

    doc = SimpleDocTemplate(
        str(pdf_path),
        pagesize=A4,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        title="Agentic Diagnostic Report",
        author="Agentic Data Parsing Engine",
    )

    story = []

    for line in markdown_content.splitlines():
        flowable = markdown_line_to_flowable(line, styles)
        story.append(flowable)

    doc.build(
        story,
        onFirstPage=add_footer,
        onLaterPages=add_footer,
    )

    return pdf_path